version: '3.1'

services:
  node_a:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_distribuido
      MYSQL_USER: devmaster
      MYSQL_PASSWORD: "@DevMaster123"
    ports:
      - "3306:3306"

  node_b:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto_distribuido
      MYSQL_USER: devmaster
      MYSQL_PASSWORD: "@DevMaster123"
    ports:
      - "3307:3306"